global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'sampleapp'
    scrape_interval: 5s
    static_configs:
      - targets: ['sampleapp:8080']