apiVersion: 1
notifiers:
  - name: SlackNotify
    type: slack
    uid: notifier1
    # either
    #org_id: 2
    # or
    #org_name: Main Org.
    is_default: true
    send_reminder: true
    frequency: 1m
    disable_resolve_message: false
    # See `Supported Settings` section for settings supported for each
    # alert notification type.
    settings:
      #recipient: 'XXX'
      uploadImage: true
      #token: 'xoxb' # legacy setting since Grafana v7.2 (stored non-encrypted)
      url: ~SLACK_URL~ # since Grafana v7.2 (stored non-encrypted)
    # Secure settings that will be encrypted in the database (supported since Grafana v7.2). See `Supported Settings` section for secure settings supported for each notifier.
      #secure_settings:
       # token: 'PJqSYGVAO0cBcxKn7ex4jSKb'
       # url: 